# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('path', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('short_name', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('main_bg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IconSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Section')),
                ('images', models.ManyToManyField(to='app.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.section',),
        ),
        migrations.CreateModel(
            name='ImageSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Section')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.section',),
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Section')),
                ('paragraphs', models.ManyToManyField(to='app.Paragraph')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.section',),
        ),
        migrations.AddField(
            model_name='section',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_app.section_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(to='app.Section'),
        ),
    ]
