# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('count', models.IntegerField()),
                ('images', models.ManyToManyField(to='app.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='imagesection',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='iconsection',
            name='images',
        ),
        migrations.AddField(
            model_name='iconsection',
            name='imageBars',
            field=models.ManyToManyField(to='app.ImageBar'),
        ),
    ]
