# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160603_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='css_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='imagebar',
            name='css_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='css_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='css_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
