# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160603_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
